#!/usr/bin/env bash
set -euo pipefail

# Skern Manual Test Scenarios — Interactive Report Generator
# Reads EXPECTED.md checklists from each scenario, prompts the developer
# for pass/fail/skip, and produces a timestamped markdown report.

TEST_ROOT="/tmp/skern-manual-tests"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPORTS_DIR="$SCRIPT_DIR/reports"

echo "=== Skern Manual Test Report ==="
echo ""

# --- Preflight ---

if [ ! -d "$TEST_ROOT" ]; then
  echo "ERROR: Test root not found at $TEST_ROOT"
  echo "Run 'make test-manual-setup' first."
  exit 1
fi

# Get metadata
SKERN_VERSION="$(skern version 2>/dev/null | head -1 || echo "unknown")"
REPORT_DATE="$(date -u +%Y-%m-%d)"
REPORT_TIME="$(date -u +%H%M%S)"
REPORT_TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
OS_INFO="$(uname -s) $(uname -r)"

echo -n "Your name (for the report): "
read -r TESTER_NAME
[ -z "$TESTER_NAME" ] && TESTER_NAME="anonymous"

echo ""

# --- Counters ---

TOTAL=0
PASS=0
FAIL=0
SKIP=0

# --- Collect results ---

# We'll build the report body in a variable
REPORT_BODY=""

for scenario_dir in "$TEST_ROOT"/*/; do
  [ ! -d "$scenario_dir" ] && continue
  scenario_name="$(basename "$scenario_dir")"

  expected_file="$scenario_dir/EXPECTED.md"
  if [ ! -f "$expected_file" ]; then
    continue
  fi

  echo "────────────────────────────────────────"
  echo "Scenario: $scenario_name"
  echo "────────────────────────────────────────"

  # Show the prompt summary (first heading from PROMPT.md)
  prompt_file="$scenario_dir/PROMPT.md"
  if [ -f "$prompt_file" ]; then
    prompt_title="$(grep -m1 '^# ' "$prompt_file" | sed 's/^# //')"
    echo "  $prompt_title"
  fi
  echo ""

  # Parse checklist items from EXPECTED.md
  SCENARIO_RESULTS=""
  scenario_total=0
  scenario_pass=0
  scenario_fail=0
  scenario_skip=0

  while IFS= read -r line; do
    # Extract the checklist text (after "- [ ] ")
    item="${line#*\] }"

    scenario_total=$((scenario_total + 1))
    TOTAL=$((TOTAL + 1))

    echo "  [$scenario_total] $item"
    echo -n "        (p)ass / (f)ail / (s)kip? "
    read -r verdict

    case "$verdict" in
      p|P|pass)
        PASS=$((PASS + 1))
        scenario_pass=$((scenario_pass + 1))
        mark="PASS"
        ;;
      f|F|fail)
        FAIL=$((FAIL + 1))
        scenario_fail=$((scenario_fail + 1))
        mark="FAIL"
        ;;
      *)
        SKIP=$((SKIP + 1))
        scenario_skip=$((scenario_skip + 1))
        mark="SKIP"
        ;;
    esac

    SCENARIO_RESULTS="${SCENARIO_RESULTS}| ${mark} | ${item} |
"
  done < <(grep -E '^\- \[ \] ' "$expected_file")

  echo ""
  echo "  Scenario result: $scenario_pass pass, $scenario_fail fail, $scenario_skip skip (of $scenario_total)"
  echo ""

  # Determine scenario status
  if [ "$scenario_fail" -gt 0 ]; then
    scenario_status="FAIL"
  elif [ "$scenario_skip" -eq "$scenario_total" ]; then
    scenario_status="SKIP"
  else
    scenario_status="PASS"
  fi

  REPORT_BODY="${REPORT_BODY}
### ${scenario_name} — ${scenario_status}

| Result | Criterion |
|--------|-----------|
${SCENARIO_RESULTS}
"
done

# --- Generate report ---

mkdir -p "$REPORTS_DIR"
REPORT_FILE="$REPORTS_DIR/${REPORT_DATE}-${REPORT_TIME}.md"

cat > "$REPORT_FILE" <<EOF
# Skern Manual Test Report

| Field | Value |
|-------|-------|
| Date | ${REPORT_TIMESTAMP} |
| Tester | ${TESTER_NAME} |
| Skern Version | ${SKERN_VERSION} |
| OS | ${OS_INFO} |

## Summary

| Metric | Count |
|--------|-------|
| Total | ${TOTAL} |
| Pass | ${PASS} |
| Fail | ${FAIL} |
| Skip | ${SKIP} |

## Results
${REPORT_BODY}
---

Generated by \`tests/manual/report.sh\`
EOF

echo "════════════════════════════════════════"
echo "=== Results: $TOTAL total, $PASS pass, $FAIL fail, $SKIP skip ==="
echo ""
echo "Report saved to: $REPORT_FILE"

if [ "$FAIL" -gt 0 ]; then
  exit 1
fi
